# Generated by Django 2.2.14 on 2020-12-07 07:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=200)),
                ('publicacion', models.CharField(max_length=200)),
                ('comentarios', models.ManyToManyField(related_name='publicaciones', to='comentarios.Comentario')),
                ('tag', models.ManyToManyField(related_name='publicaciones', to='tags.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
